#! /bin/sh

RED="\033[0;31m"
RESET="\033[0m"

echo "--- Running Build ---"
./gradlew clean build
if [ "$?" -ne 0 ]; then
  echo "${RED} ***** BUILD FAILED ***** ${RESET}"
  exit 1
fi

#echo "--- Running Integration Tests ---"
#./gradlew integrationTest
#if [ "$?" -ne 0 ]; then
#  echo "${RED} ***** INTEGRATION TESTS FAILED ***** ${RESET}"
#  exit 1
#fi

exit 0
