name: Java CI with Gradle

on:
  push:
    branches: [ main, release-1.0 ]
  pull_request:
    branches: [ main, release-1.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: gradle clean build
      - name: Test with Gradle
        run: gradle clean test
